# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
 branches:
   include:
     - master
 paths:
   include:
     - LearningMicroService/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/LearningMicroService*.csproj'
    displayName: 'Restore nuget packages'
  
  - task: DotNetCoreCLI@2
    inputs:
      command: build
      projects: '**/LearningMicroService*.csproj'
      arguments: '--no-restore'
    displayName: 'Build projects'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '**/*Test.csproj'
      arguments: '--no-restore --no-build'
    displayName: 'Run tests'
  
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '**/LearningMicroService.API.csproj'      
      arguments: '--configuration $(buildConfiguration) --no-restore'
      modifyOutputPath: false
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))
    displayName: 'Publish LearningMicroService API'


